# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-06 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Пиццерия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('url', models.URLField(verbose_name='Интернет-адрес пиццерии')),
            ],
        ),
    ]
